import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsQuickStart: SidebarsConfig = {
  "quickStartSidebar": [
    { type: 'autogenerated', dirName: '.' }
  ],
};

export default sidebarsQuickStart;
