import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsShowcase: SidebarsConfig = {
  "showcaseSidebar": [
    { type: 'autogenerated', dirName: '.' }
  ],
};

export default sidebarsShowcase;
